# Generated by Django 4.1.7 on 2023-02-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freetimecardapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clock_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('clock_in_time', models.CharField(max_length=200)),
                ('clock_out_time', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
