# Generated by Django 4.1.7 on 2023-02-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freetimecardapp', '0002_clock_data_delete_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clock_data',
            name='clock_out_time',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
