# Generated by Django 4.1.7 on 2023-02-26 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freetimecardapp', '0003_alter_clock_data_clock_out_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clock_data',
            name='clock_out_time',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
