# Generated by Django 4.1.7 on 2023-02-26 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freetimecardapp', '0004_alter_clock_data_clock_out_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='clock_data',
            name='clock_in_date',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='clock_data',
            name='clock_out_date',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clock_data',
            name='clock_in_time',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='clock_data',
            name='clock_out_time',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clock_data',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
