# Generated by Django 4.1.7 on 2023-02-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freetimecardapp', '0005_clock_data_clock_in_date_clock_data_clock_out_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clock_data',
            name='clock_in_date',
            field=models.CharField(default='02/26/23', max_length=20),
        ),
        migrations.AlterField(
            model_name='clock_data',
            name='clock_out_date',
            field=models.CharField(default='02/26/23', max_length=20, null=True),
        ),
    ]
